CREATE TABLE NEWS
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE      TEXT,
    CONTENT    TEXT,
    URL        VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
) DEFAULT CHARSET = UTF8MB4;

CREATE TABLE LINK_TO_BE_PROCESSED
(
    LINK VARCHAR(1000)
);
CREATE TABLE LINK_PROCESSED
(
    LINK VARCHAR(1000)
);